//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPointSlideThumbnailsAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPointSlideThumbnailsAddIn.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string about_ok {
            get {
                return ResourceManager.GetString("about_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About .
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        internal static string lblBackToGrid {
            get {
                return ResourceManager.GetString("lblBackToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string lblEnd {
            get {
                return ResourceManager.GetString("lblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPoint Slide Thumbnails Add-in.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string toolTipAbout {
            get {
                return ResourceManager.GetString("toolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Slides.
        /// </summary>
        internal static string toolTipBackToGrid {
            get {
                return ResourceManager.GetString("toolTipBackToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock to bottom.
        /// </summary>
        internal static string toolTipDockBottom {
            get {
                return ResourceManager.GetString("toolTipDockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock to right.
        /// </summary>
        internal static string toolTipDockRight {
            get {
                return ResourceManager.GetString("toolTipDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Slideshow.
        /// </summary>
        internal static string toolTipEnd {
            get {
                return ResourceManager.GetString("toolTipEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string toolTipLeft {
            get {
                return ResourceManager.GetString("toolTipLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string toolTipRight {
            get {
                return ResourceManager.GetString("toolTipRight", resourceCulture);
            }
        }
    }
}
